name: Add risk label

on:
  pull_request:
    types: [opened, edited]

jobs:
  add-risk-label:
    uses: alextheman231/github-actions/.github/workflows/add-risk-label.yml@da716aafd4a67029c0bee56a84afbc96345531dc # v12.7.1
    permissions:
      pull-requests: write
    with:
      APP_ID: ${{ vars.ALEX_UP_BOT_APP_ID }}
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.ALEX_UP_BOT_PRIVATE_KEY }}
