name: Apply Terraform Configuration

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  TF_CLOUD_ORGANIZATION: "alextheman"
  TF_TOKEN_app_terraform_io: ${{ secrets.TFE_TOKEN }}
  TF_WORKSPACE: "infrastructure"

jobs:
  terraform-apply:
    if: ${{ github.repository == 'alextheman231/infrastructure' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Do not allow anyone other than AlexMan123456 to directly apply manually
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          if [[ "$GITHUB_ACTOR" !=  "AlexMan123456" ]]; then
            echo "Only AlexMan123456 is allowed to manually apply the configuration."
            exit 1
          fi

      - name: Checkout the repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
        with:
          terraform_version: 1.15

      - name: Initialise Terraform
        run: terraform init

      - name: Verify the plan
        id: plan
        run: terraform plan -detailed-exitcode -out=tfplan
        continue-on-error: true

      - name: Fail if the plan gave exit code 1
        if: steps.plan.outputs.exitcode == '1'
        run: exit 1

      - name: Approve and apply the configuration
        if: steps.plan.outputs.exitcode == '2'
        run: terraform apply tfplan
