name: Change request

on:
  workflow_dispatch:
    inputs:
      reason:
        description: A short explanation for the reason behind the change.
        required: true
      description:
        description: A further description of the change.
        required: false
        default: Reapply the configuration

jobs:
  create-change-request:
    permissions:
      contents: write
      pull-requests: write
    if: ${{ github.repository == 'alextheman231/infrastructure' }}
    uses: alextheman231/github-actions/.github/workflows/create-change-request.yml@9f2644441ec84b8bbaf71a57e3eb4cfe8c0be8cc # v12.2.0
    with:
      actor: ${{ github.actor }}
      reason: ${{ inputs.reason }}
      description: ${{ inputs.description }}
