name: Terraform CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  merge_group:
    types: [checks_requested]

jobs:
  terraform-lint-ci:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Use PNPM
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0
        with:
          run_install: false

      - name: Use Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 22
          cache: "pnpm"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85 # v4.0.0
        with:
          terraform_version: 1.14.3

      - name: Install dependencies
        run: pnpm install

      - name: Initialise Terraform
        run: terraform init -backend=false

      - name: Run linting checks
        run: pnpm run lint

  terraform-plan-ci:
    permissions:
      checks: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85 # v4.0.0
        with:
          terraform_version: 1.14.3

      - name: Run the plan
        uses: op5dev/tf-via-pr@8d74c69c2863bcb3bb87c8313ca46bc2fc89b98a # v13.7.3
        id: plan-output
        with:
          command: plan
          plan-encrypt: ${{ secrets.PASSPHRASE }}
          comment-pr: never
          expand-diff: true
          expand-summary: true
          arg-lock-timeout: 30m
        env:
          TF_CLOUD_ORGANIZATION: "alextheman"
          TF_TOKEN_app_terraform_io: "${{ secrets.TFE_TOKEN }}"
          TF_WORKSPACE: "infrastructure"

      - name: Extract run ID
        id: get-run-id
        env:
          COMMENT_BODY: ${{ steps.plan-output.outputs.comment-body }}
        run: |
          RUN_ID=$(echo "$COMMENT_BODY" | grep -oE 'https://app\.terraform\.io/app/[^/]+/[^/]+/runs/(run-[a-zA-Z0-9]+)' | sed 's#.*/##')
          echo "run-id=$RUN_ID" >> $GITHUB_OUTPUT

      - name: Discard the plan run
        uses: hashicorp/tfc-workflows-github/actions/discard-run@8e08d1ba957673f5fbf971a22b3219639dc45661 # v1.3.2
        with:
          token: ${{ secrets.TFE_TOKEN }}
          run: ${{ steps.get-run-id.outputs.run-id }}
          comment: "Discarded from GitHub Actions CI"

      - name: Save plan output
        if: ${{ github.event_name == 'pull_request' }}
        env:
          COMMENT_BODY: ${{ steps.plan-output.outputs.comment-body }}
        run: echo "$COMMENT_BODY" > plan.txt

      - name: Upload the plan to be used in pull request comment
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: terraform-plan
          path: plan.txt

  comment-terraform-plan:
    needs: [terraform-plan-ci]
    if: ${{ github.event_name == 'pull_request' }}
    permissions:
      actions: read
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Download the plan
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: terraform-plan

      - name: Save the plan to the GitHub Output
        id: get-plan
        run: |
          PLAN=$(cat plan.txt)
          echo "comment-body<<EOF" >> $GITHUB_OUTPUT
          echo "$PLAN" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Get alex-up-bot GitHub token
        id: app-token
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3.0.0
        with:
          app-id: ${{ secrets.ALEX_UP_BOT_APP_ID }}
          private-key: ${{ secrets.ALEX_UP_BOT_PRIVATE_KEY }}

      - name: Find existing comment
        uses: peter-evans/find-comment@b30e6a3c0ed37e7c023ccd3f1db5c6c0b0c23aad # v4.0.0
        id: find-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "alex-up-bot[bot]"
          body-includes: # HCP Terraform Plan Output

      - name: Comment the plan on the pull request
        uses: peter-evans/create-or-update-comment@e8674b075228eee787fea43ef493e45ece1004c9 # v5.0.0
        id: create-comment
        with:
          token: ${{ steps.app-token.outputs.token }}
          issue-number: ${{ github.event.pull_request.number }}
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          edit-mode: replace
          body: |
            # HCP Terraform Plan Output

            ${{ steps.get-plan.outputs.comment-body }}

  actions-ci:
    permissions:
      contents: read
    uses: alextheman231/github-actions/.github/workflows/actions-ci.yml@d7dc056201417cb361b653afa9a09b5900e245e4 # v11.0.4
