name: Terraform CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  merge_group:
    types: [checks_requested]

jobs:
  terraform-lint-ci:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Use PNPM
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          run_install: false

      - name: Use Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 22
          cache: "pnpm"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
        with:
          terraform_version: 1.15

      - name: Install dependencies
        run: pnpm install

      - name: Initialise Terraform
        run: terraform init -backend=false

      - name: Run linting checks
        run: pnpm run lint

  terraform-plan-ci:
    permissions:
      checks: write
      contents: read
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    env:
      TF_CLOUD_ORGANIZATION: "alextheman"
      TF_TOKEN_app_terraform_io: ${{ secrets.TFE_TOKEN }}
      TF_WORKSPACE: "infrastructure"
    outputs:
      plan_summary: ${{ steps.plan_summary.outputs.plan_summary }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
        with:
          terraform_version: 1.15

      - name: Initialise Terraform
        run: terraform init

      - name: Run the plan
        id: plan
        run: |
          set -o pipefail
          terraform plan -no-color 2>&1 | tee raw-plan.md

      - name: Save plan output
        run: |
          awk '
          /Terraform used the selected providers to generate the following execution/ {
            printing=1
          }

          /Terraform will perform the following actions:/ {
            printing=1
          }

          /No changes\. Your infrastructure matches the configuration\./ {
            printing=1
          }

           /^─────────────────────────────────────────────────────────────────────────────$/ {
            exit
          }

          printing
          ' raw-plan.md > plan.md

      - name: Save plan summary
        id: plan_summary
        run: |
          PLAN_SUMMARY=$(grep -E '^(Plan:|No changes\.)' raw-plan.md | head -n1)
          echo "plan_summary=$PLAN_SUMMARY" >> $GITHUB_OUTPUT

      - name: Upload the plan to be used in pull request comment
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: terraform-plan
          path: plan.md

  comment-terraform-plan:
    needs: [terraform-plan-ci]
    if: ${{ github.event_name == 'pull_request' }}
    permissions:
      actions: read
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Download the plan
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: terraform-plan

      - name: Save the plan to the GitHub Output
        id: get-plan
        run: |
          PLAN=$(cat plan.md)
          echo "comment-body<<EOF" >> $GITHUB_OUTPUT
          echo "$PLAN" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Get alex-up-bot GitHub token
        id: app-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ vars.ALEX_UP_BOT_APP_ID }}
          private-key: ${{ secrets.ALEX_UP_BOT_PRIVATE_KEY }}
          permission-contents: read
          permission-pull-requests: write

      - name: Find existing comment
        uses: peter-evans/find-comment@b30e6a3c0ed37e7c023ccd3f1db5c6c0b0c23aad # v4.0.0
        id: find-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "alex-up-bot[bot]"
          body-includes: # HCP Terraform Plan Output

      - name: Comment the plan on the pull request
        uses: peter-evans/create-or-update-comment@e8674b075228eee787fea43ef493e45ece1004c9 # v5.0.0
        id: create-comment
        with:
          token: ${{ steps.app-token.outputs.token }}
          issue-number: ${{ github.event.pull_request.number }}
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          edit-mode: replace
          body: |
            # HCP Terraform Plan Output

            <details open>
            <summary>${{ needs.terraform-plan-ci.outputs.plan_summary }}</summary>

            ```hcl
            ${{ steps.get-plan.outputs.comment-body }}
            ```

            </details>

      - name: Give a 30-second plan review window before passing
        run: sleep 30

  actions-ci:
    permissions:
      contents: read
    uses: alextheman231/github-actions/.github/workflows/actions-ci.yml@3a7c224f60dbd26c8e2f31738236b6cbc8dd96e7 # v12.0.0
