name: Terraform CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  merge_group:
    types: [checks_requested]

env:
  TF_CLOUD_ORGANIZATION: "alextheman"
  TF_API_TOKEN: "${{ secrets.TFE_TOKEN }}"
  TF_WORKSPACE: "infrastructure"

jobs:
  terraform-ci:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Use PNPM
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        with:
          run_install: false

      - name: Use Node.js
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: 22
          cache: "pnpm"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: 1.14.3

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@4cb9feea73331a35b422df102992a03a44a3bb33 # v6.2.1
        with:
          tflint_version: v0.52.0
          cache: true

      - name: Install dependencies
        run: pnpm install

      - name: Initialise Terraform
        run: terraform init -backend=false

      - name: Run linting checks
        run: pnpm run lint

      - name: Upload Configuration
        uses: hashicorp/tfc-workflows-github/actions/upload-configuration@8e08d1ba957673f5fbf971a22b3219639dc45661 # v1.3.2
        id: plan-upload
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          directory: "./"
          speculative: true

      - name: Create Plan Run
        uses: hashicorp/tfc-workflows-github/actions/create-run@8e08d1ba957673f5fbf971a22b3219639dc45661 # v1.3.2
        id: plan-run
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          configuration_version: ${{ steps.plan-upload.outputs.configuration_version_id }}
          plan_only: true

      - name: Get Plan Output
        uses: hashicorp/tfc-workflows-github/actions/plan-output@8e08d1ba957673f5fbf971a22b3219639dc45661 # v1.3.2
        id: plan-output
        with:
          plan: ${{ fromJSON(steps.plan-run.outputs.payload).data.relationships.plan.data.id }}

      - name: Get alex-up-bot GitHub token
        id: app-token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        with:
          app-id: ${{ secrets.ALEX_UP_BOT_APP_ID }}
          private-key: ${{ secrets.ALEX_UP_BOT_PRIVATE_KEY  }}

      - name: Find Comment
        uses: peter-evans/find-comment@b30e6a3c0ed37e7c023ccd3f1db5c6c0b0c23aad # v4.0.0
        if: ${{ github.event_name == 'pull_request' }}
        id: find-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "alex-up-bot[bot]"
          body-includes: #### HCP Terraform Plan Output

      - name: Comment the plan on the pull request
        uses: peter-evans/create-or-update-comment@e8674b075228eee787fea43ef493e45ece1004c9 # v5.0.0
        if: ${{ github.event_name == 'pull_request' }}
        id: create-comment
        with:
          token: ${{ steps.app-token.outputs.token }}
          issue-number: ${{ github.event.pull_request.number }}
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          body: |
            #### HCP Terraform Plan Output
            ```
            Plan: 
            ${{ steps.plan-output.outputs.add }} to add,
            ${{ steps.plan-output.outputs.change }} to change,
            ${{ steps.plan-output.outputs.destroy }} to destroy.
            ```
            [HCP Terraform Plan](${{ steps.plan-run.outputs.run_link }})

  actions-ci:
    permissions:
      contents: read
    uses: alextheman231/github-actions/.github/workflows/actions-ci.yml@3db51f2a57ee95cda50310b3856cfdc0ae171cf7 # v8.3.3
